[page]
language = "en"
paper = "a4"
margins = {left = "1cm", top = "1cm", right = "1cm", bottom = "1cm"}
colors = {accent = "#0395DE", dark = "#212529", light = "#F2F2F2"}

[header]
name = {font = "libertinus serif", size = "32pt"}
role = {font = "libertinus serif", role_size = "18pt", loc_size = "12pt"}
profile-text = {font = "libertinus serif", size = "10pt"}
line-icons = {font = "libertinus serif", size = "10pt"}

[header.corner]
size = {width = "30%", height = "16%", y-offset = "3mm"}
radius = {bottom-left = "25%", top-left = "0%", top-right = "0%", bottom-right = "0%"}

[header.image]
blur = "18pt"
stroke = "3pt"
radius = {bottom-left = "50%", top-left = "50%", top-right = "50%", bottom-right = "50%"}

[accent-column]
width = "35%"
radius = {bottom-left = "0%", top-left = "0%", top-right = "20%", bottom-right = "0%"}
text = {font="libertinus serif", head_size="", body_size=""}

[main-column]
text = {font="libertinus serif", head_size="", body_size=""}
