[setup]
  language = "en"
  paper = "a4"
  margins = {left = "1cm", right = "1cm", top = "1cm", bottom = "1cm"} # One line

[colors]
  accent = "#0395DE"
  dark = "#212529"
  light = "#F2F2F2"

[accent_corner]
  width = "30%"
  height = "16%"
  v_offset = "0.25cm"
  radius = {bottom-left = "20%", bottom-right = "0%", top-left = "0%", top-right = "0%"}

[profile_image]
  radius = {bottom-left = "50%", bottom-right = "50%", top-left = "50%", top-right = "50%"}
  blur = "10pt"
  stroke = "3pt"

[accent_column]
  width = "35%"
  gutter = "7%"
  radius = {bottom-left = "0%", bottom-right = "0%", top-left = "0%", top-right = "20%"}
