[page]
language = "en"
paper = "a4"
margins = {left = "1cm", top = "1cm", right = "1cm", bottom = "1cm"}
colors = {accent = "#0395DE", dark = "#212529", light = "#F2F2F2"}

[header]
name = {font = "arial", size = "32pt"}
role = {font = "arial", role_size = "18pt", loc_size = "10pt"}
profile-text = {font = "arial", size = "18pt"}
line-icons = {font = "arial", size = "10pt", y-offset = "10mm"}

[header.corner]
size = {width = "30%", height = "16%", y-offset = "3mm"}
radius = {bottom-left = "20%", top-left = "0%", top-right = "0%", bottom-right = "0%"}

[header.image]
blur = "10pt"
stroke = "3pt"
radius = {bottom-left = "50%", top-left = "50%", top-right = "50%", bottom-right = "50%"}

[accent-column]
width = "35%"
radius = {bottom-left = "0%", top-left = "0%", top-right = "20%", bottom-right = "0%"}
text = {font="arial", head_size="", body_size=""}

[main-column]
text = {font="arial", head_size="", body_size=""}
