[metadata]
title = ""
author = ""
description = ""
keywords = ""

[header]
name = "Name Middle Last"
role = "Role"
location = "Earth, Solar System"
profile-img = "template/assets/images/elonmusk.jpg"
profile-text = "My profile summary"
line_1 = [
  {icon = "fa-phone", text = "+00 000 000 000", link = ""},
  {icon = "fa-envelope", text = "hola@domain.tld", link = "mailto:hola:domain.tld"},
]
line_2 = [
  {icon = "fa-gears", text = "Portfolio", link = "https://domain.tld/Portfolio"},
]

[[accent-column]]

[[main-column]]

[[extended]]
